#!/bin/bash
#Setup our app

docker-compose up -d

sleep 5

path=$(ls -A 'app/')
if [[ ! -z "$path" ]]; then
    echo "folder is not empty"
    if [ -f app/.env ]; then
        echo ".env exist"
    else
        echo ".env doesn't exist"
        cp app/.env.example app/.env
        echo ".env copied from .env.example"
    fi
    docker-compose run --rm php74-service composer install
    docker-compose run --rm php74-service php bin/console d:d:c
    docker-compose run --rm node-service yarn install
    docker-compose run --rm node-service yarn build
else
    echo "folder is empty"
    docker-compose run --rm php74-service composer create-project symfony/website-skeleton .
fi

echo "END"
